### ISSUE TITLE
random issues to consider

### ISSUE THREAD

**Issue by braynshock** [v1k0d3n/bootkube-ci#12]
@v1k0d3n , Just wanted to mention these...
1. Not sure which combination of packages. But i've had issues with sudo after installing ZFS then running bootkube (i think it's the docker package that is causing it).... Sudo fails, long story short it's an issue with /dev/null permissions, and some package adding a configuration line to /etc/sudoers to log to /dev/null... manually edited to remove, and it works again.

2. Another issue I was having was with having to manually add kubernetes.default to my /etc/hosts file. After doing that twice, i realized i could have just edited .bootkube.env to be my server's hostname. (User error)
**This issue was causing my containers to come up without IP addresses... and the api-server to crash constantly.

3. DNSmasq was also causing random crashing issues for the containers, so I manually disabled DNSmasq and fixed /etc/resolv.conf.

4. In addition, I don't think bootkube-clean.sh is putting it back the way it was before bootkube-up.sh...

Anyway, hope these help someone else.

I now have a clean metal install, with a ZFS storage array, just need to figure out how to point etcd to use it.

**Comment by braynshock** [comment]
i created a pair of pull requests... I wanted to be able to modify the manifests that are rendered during bootkube-up.sh, but bootkube-clean.sh was removing them all. So these allowed me to stop kubernetes, modify the manifests, and then restart it.

These will need fixed, have a problem with certificate... been fighting with it for a bit, haven't quite figured out what's wrong, but there might be something else i'm missing too.

**Comment by v1k0d3n** [comment]
@braynshock yeah, i'm going to stop touching `/etc/resolv.conf` and just use `head`/`base`.

did you ever figure out some of the issues above? i'm really interested in them and would like to have them resolved. sorry for not responding. if not and you have some more details...i can start chasing them down.

**Comment by braynshock** [comment]
@v1k0d3n ... i am still having issues with DNS... I've manually diabled dnsmasq at the OS layer... And then after the up script finishes, I can go fix resolv.conf, and then it will eventually come up.

Currently i have it up and running, with fabric8 running on top. I've configured persistent volumes for jenkins, sonorqube, gog, docker-registry, and nexus. They are pointing to my local ZFS Storage Array.

BUT, the kube-dns service crashes about every 15min or so.

I'm also in the middle of configuring ingresses, but running firefox thru ssh -X, works fine too.

once I complete the ingresses, I plan on adding 4 x ARM64 SoC as kube-workers.

**Comment by braynshock** [comment]
![image](https://user-images.githubusercontent.com/8523285/27205468-043d8ab8-51ff-11e7-85f4-d6c3bef8513e.png)

**Comment by v1k0d3n** [comment]
The dns issues are interesting to me. I'll try this today. I'd be fine with keeping this issue open if you want while we figure it out. Your call here. Sorry, there were a couple of crazy days and I meant to get back to it at some point.

I'll test a little on my end. The project by default is configured to use Ceph as a backend persistent store. This is the reason for the 10.96.0.x first dns entry pointing to kubedns and also the hyperkube image change. Ceph is installed via a Helm chart. It's definitely not going to be as fast/efficient as what you're doing with ZFS, but it's there to test with if you want.
